server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
#    context-path: /api/
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: xxx
      # 是否启动日志
      enabled: false
      # 日志格式
      pattern: common
      # 日志文件名前缀
      prefix: access_log
      # 日志文件名后缀
      suffix: log
    # HTTP POST请求最大的大小
    max-http-post-size: 0
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程。
    #该值不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 128
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
#    buffers-per-region: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///stephanie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 150
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #  springboot 2.6兼容Swagger2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enabled: true

dingtalk:
  appKey: dingie2zpz1moh4vwckl
  appSecret: TSmK0WB3Du5BBmwifsULoIE478fDaXmZUI8ZMhx0JVj1UZMnryWKzuysRipZUNq-
  aes_key: woIag2tuEhhFxKFcMzZmFl37bQkmW7oza5oImoUNR32
  token: woIag2tuEhhFxKFcMzZmFl37bQkmW7oza5oImoUNR32

